[package]
name = "rust-boost"
version = "0.1.0"
authors = ["Julaiti Alafate <jalafate@gmail.com>"]

[dependencies]
log = "0.4.1"
env_logger = "0.5.5"
ordered-float = "0.5.0"
rand = "0.4.2"
rayon = "1.0.0"
