---
# training_filename: /Users/arapat/Documents/data/splice/training-data-100K.libsvm
training_filename: /Users/arapat/Documents/data/splice/training-data.libsvm
training_is_binary: false
training_bytes_per_example: 0
testing_filename: /Users/arapat/Documents/data/splice/training-data-10K.libsvm
testing_is_binary: false
testing_bytes_per_example: 0
num_examples: 50000000
num_testing_examples: 10000
num_features: 565
range:
  start: 0
  end: 564
max_sample_size: 20000
max_bin_size: 10
default_gamma: 0.25
num_iterations: 64
max_trials_before_shrink: 1000000
channel_size: 128
buffer_size: 50000
batch_size: 10000
sampler_num_threads: 2
sampler_init_grid_size: 1.0
sampler_average_window_size: 1000
num_examples_per_block: 128
disk_buffer_filename: stratified.bin
num_assigners: 2
num_selectors: 2
network: []
port: 8888
local_name: local_worker