---
# training_filename: /Users/arapat/Documents/data/splice/training-data-100K.libsvm
training_filename: /mnt/training-shuffled.libsvm
training_is_binary: false
training_bytes_per_example: 0
testing_filename: /mnt/testing-correct.libsvm
testing_is_binary: false
testing_bytes_per_example: 574
num_examples: 50000000
num_testing_examples: 4627840
num_features: 565
range:
  start: 0
  end: 564
max_sample_size: 20000
max_bin_size: 10
default_gamma: 0.25
num_iterations: 0
max_trials_before_shrink: 1000000
channel_size: 65536
buffer_size: 2000000
batch_size: 10000
parallel_sampling: true,
sampler_num_threads: 1
sampler_init_grid_size: 1.0
sampler_average_window_size: 1000
num_examples_per_block: 8192
disk_buffer_filename: stratified.bin
num_assigners: 1
num_samplers: 3
network: []
port: 8888
local_name: local_worker
